### PR TITLE
Joined the guide into a single file

### PR DESCRIPTION
**Pull request by JesperIRL**
I have left a forwarding pointer in the old files in case anyone has a link to the guide somewhere. Not sure if this is needed. Maybe it's better to just remove all the files directly?

I did remove jbslabels.md since that file hasn't been published on the web server yet.

I didn't make any changes in the content except for removing references to getSource.md, hgHelp.md, and tClone.md since they are outdated and shouldn't be inlined in the guide. I also removed all TBD and sections with no content. Notes has been added in the todo list in README.md for all sections and TBDs that was removed.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Reviewers
 * [Stuart Marks](https://openjdk.java.net/census#smarks) (@stuart-marks - no project role)
 * [Iris Clark](https://openjdk.java.net/census#iris) (@irisclark - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/guide pull/28/head:pull/28`
`$ git checkout pull/28`

### CODE REVIEW

**Comment by aioobe** [comment]
I see a lot of deletions and few additions. Surely some content has been removed?

**Comment by JesperIRL** [comment]
> I see a lot of deletions and few additions. Surely some content has been removed?

No actual content should have been removed. If so, that is a bug. The parts that has been removed are:

* Prev - TOC - Next  -links on top and bottom of each page
* The index is now automatically generated
* Sections with no actual content like bugDatabase.md has been removed and gotten a note in the todo-list in the readme
* faq.md was removed since it explicitly said that it was a temporary holder for questions that were to be answered in the guide - now replaced by the todo-list

Depending on what metric you use to count deletions and additions a contributing factor could be that I have removed a lot of linebreaks.

**Review by stuart-marks — APPROVED** [review]

**Comment by stuart-marks** [comment]
FWIW I've reviewed these changes, though I'm not a Reviewer on the Guide project.

I see that most of the contents is preserved, though some placeholder sections that were never written (e.g., on TCK testing) have been removed, which makes sense, as they probably are irrelevant at this point. I also note that a LOT of the material covers Mercurial, which of course will need to be rewritten for the git/GitHub/Skara workflow.

**Review by irisclark — APPROVED** [review]
Nice consolidation!  As far as I can tell, all of the relevant text has been retained.  As expected, most deletions are structural (navigation, line breaks) and a few empty sections are deleted.

**Comment by JesperIRL** [comment]
Thank you for the reviews Stuart and Iris!

**Pull request closed without merging**
