### PR TITLE
Add gitignore for build directory

### PR DESCRIPTION
**Pull request by karianna**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Reviewers
 * Jesper Wilhelmsson ([jwilhelm](@JesperIRL) - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/guide pull/12/head:pull/12`
`$ git checkout pull/12`

### CODE REVIEW

**Comment by JesperIRL** [comment]
Looks good. Thanks for adding this! I've been meaning to :-)
I'll sponsor this as you are not an author in this project yet.

**Comment by karianna** [comment]
> Looks good. Thanks for adding this! I've been meaning to :-)
> I'll sponsor this as you are not an author in this project yet.

Thanks.  Any way of getting the bot to recognize that I _have_ signed the OCA already?

**Comment by JesperIRL** [comment]
Please follow the instruction above to open an issue in JBS to get your user name tied to your GitHub account. Robin is standing by to approve it 🙂

**Comment by karianna** [comment]
> Please follow the instruction above to open an issue in JBS to get your user name tied to your GitHub account. Robin is standing by to approve it 🙂

Hi Jesper, sadly I'm only a Contributor, not an Author, and therefore cannot open an issue in JBS...

**Pull request closed without merging**
