### PR TITLE
Add notes on avoiding spurious introduction of labels.

### PR DESCRIPTION
**Pull request by stuart-marks**
Include discussion of using label autocomplete to ensure that an existing label is used.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed

### Reviewers
 * [Igor Ignatyev](https://openjdk.java.net/census#iignatyev) (@iignatev - no project role)
 * [Iris Clark](https://openjdk.java.net/census#iris) (@irisclark - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/guide pull/31/head:pull/31`
`$ git checkout pull/31`

### CODE REVIEW

**Review by iignatev — APPROVED** [review]

**Review by irisclark — APPROVED** [review]
Yes!

Historical Note: The use of labels has changed over time.  In very early versions of the JDK bug system, the equivalent labels field was treated as an index.  Because all of that information has been retained, the set of existing labels is huge!

**Comment by stuart-marks** [comment]
@JesperIRL Can you sponsor this change? (If you're ok with it of course.) Iris has reviewed it so I think it falls to you to sponsor it. Thanks.

**Comment by JesperIRL** [comment]
Good addition. Thanks!

**Pull request closed without merging**
